core.entity_view_display.*.*.*.third_party.layout_builder_restrictions:
  type: sequence
  label: 'Layout Builder Restrictions plugin configuration'
  sequence:
    - type: layout_builder_restrictions.[%key]

layout_builder_restrictions.entity_view_mode_restriction:
  type: mapping
  label: 'Per-view-mode Layout Builder Restrictions settings'
  mapping:
    allowed_blocks:
      type: sequence
      label: 'Allowed blocks by category'
      sequence:
        type: sequence
        label: 'Allowed blocks'
        sequence:
          type: string
          label: 'Block ID'
    allowed_layouts:
      type: sequence
      label: 'Allowed layouts'
      sequence:
        type: string
        label: 'Layout ID'

layout_builder_restrictions.plugins:
  type: config_object
  label: 'Weighting and active status of Layout Builder Restrictions plugins'
  mapping:
    plugin_config:
      type: sequence
      sequence:
        type: mapping
        mapping:
          enabled:
            type: boolean
            label: 'Is the plugin enabled'
          weight:
            type: integer
            label: 'The relative order of the plugin'
