<?php

/**
 * @file
 * Contains hook implementations for Lightning Page.
 */

use Drupal\content_moderation\Plugin\WorkflowType\ContentModerationInterface;
use Drupal\Core\Plugin\ObjectWithPluginCollectionInterface;
use Drupal\field\FieldConfigInterface;
use Drupal\node\Entity\NodeType;
use Drupal\workflows\WorkflowInterface;

/**
 * Implements hook_modules_installed().
 */
function lightning_page_modules_installed(array $modules) {
  if (Drupal::isConfigSyncing()) {
    return;
  }

  if (in_array('layout_library', $modules, TRUE)) {
    /** @var \Drupal\layout_builder\Entity\LayoutEntityDisplayInterface $display */
    $display = lightning_core_entity_get_display('node', 'page');
    $display
      ->enableLayoutBuilder()
      ->setThirdPartySetting('layout_library', 'enable', TRUE)
      ->save();
  }

  if (in_array('menu_ui', $modules, TRUE)) {
    NodeType::load('page')
      ->setThirdPartySetting('menu_ui', 'available_menus', ['main'])
      ->setThirdPartySetting('menu_ui', 'parent', 'main:')
      ->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function lightning_page_field_config_insert(FieldConfigInterface $field) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  elseif ($field->id() == 'node.page.field_meta_tags') {
    lightning_core_entity_get_display('node', 'page')
      ->setComponent('field_meta_tags', [
        'type' => 'metatag_empty_formatter',
        'region' => 'content',
      ])
      ->save();

    lightning_core_entity_get_form_display('node', 'page')
      ->setComponent('field_meta_tags', [
        'type' => 'metatag_firehose',
        'region' => 'content',
      ])
      ->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function lightning_page_workflow_presave(WorkflowInterface $workflow) {
  if (Drupal::isConfigSyncing()) {
    return;
  }
  elseif ($workflow->isNew() && $workflow->id() === 'editorial' && Drupal::moduleHandler()->moduleExists('lightning_workflow')) {
    $type_plugin = $workflow->getTypePlugin();

    if ($type_plugin instanceof ContentModerationInterface) {
      $type_plugin->addEntityTypeAndBundle('node', 'page');

      // Since this hook is invoked _after_ Workflow::preSave(), we need to
      // ensure that the stored settings for the type plugin will be up-to-date
      // with the changes we've made here.
      if ($workflow instanceof ObjectWithPluginCollectionInterface) {
        foreach ($workflow->getPluginCollections() as $key => $plugin_collection) {
          $workflow->set($key, $plugin_collection->getConfiguration());
        }
      }
    }
  }
}
